# Generated by Django 2.0.4 on 2018-04-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusteradmin',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='clusteradmin',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ClusterAdmin',
        ),
    ]
